### PR TITLE
Call config.reset_config() once advise is done

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/integration-tests/issues/151

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

... requires thamos>1.13.0

**Review by KPostOffice — APPROVED** [review]

**Comment by goern** [comment]
@pacospace this PR is blocked because Qeb-Hwt  is still running. could you have a look at this

/sig cyborgs
/priority critical-urgent

**Pull request merged**
