### PR TITLE
Adjust integration tests based on adjusted responses

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/user-api/pull/1255/

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
is this response be affected as well: https://github.com/thoth-station/integration-tests/blob/b0a38fb8c81c890b29aa70b91fae789943ed917c/features/steps/python_package_index.py#L52

**Comment by fridex** [comment]
> is this response be affected as well:
> 
> https://github.com/thoth-station/integration-tests/blob/b0a38fb8c81c890b29aa70b91fae789943ed917c/features/steps/python_package_index.py#L52

Management API has a different response schema than user API (it includes also if the given index is enabled or disabled):

https://github.com/thoth-station/management-api/blob/1038d8d805d96263c07583bcec56f68cde5ff644/openapi/openapi.yaml#L586-L593

**Review by harshad16 — COMMENTED** [review]
/lgtm
thanks for the explanation

**Pull request merged**
