### PR TITLE
check solver names match a pattern

### PR DESCRIPTION
**Pull request by bissenbay**
Instead of having a minimum set of solvers requested, let's get all available solvers and check they match some pattern like Solver-`solver-{rhel|fedora}-{num}-py3{num}`.

### CODE REVIEW

**Comment by bissenbay** [comment]
@fridex PTAL

**Review by fridex — APPROVED** [review]
LGTM! :+1: :100:

**Comment by bissenbay** [comment]
> LGTM!

thanks!

**Review by pacospace — APPROVED** [review]

**Pull request merged**
